[package]
name = "inkrs"
version = "0.1.0"
authors = ["Clément Busschaert <clement.busschaert@gmail.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_test = "1.0"
serde_derive = "1.0"
itertools = "0.7.6"